FROM --platform linux/amd64 ubuntu:20.04
RUN apt-get update && apt-get install -y python3 python3-pip python3-dev gcc
WORKDIR /app
COPY . .
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install pyinstaller
RUN python3 -m PyInstaller --onefile --name sa-installer startup.py
RUN python3 -m PyInstaller --onedir --name sa-shell-fast sa/shell/shell.py
